---
AWSTemplateFormatVersion: "2010-09-09"

# A text string that describes the template. This section must always follow the template format version section.
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-description-structure.html
Description: String

# Objects that provide additional information about the template.
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/metadata-section-structure.html
Metadata: template metadata

# Values to pass to your template at runtime (when you create or update a stack). You can refer to parameters from the Resources and Outputs sections of the template.
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
Parameters: set of parameters

# Validates a parameter or a combination of parameters passed to a template during a stack creation or stack update.
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/rules-section-structure.html
Rules: set of rules

# A mapping of keys and associated values that you can use to specify conditional parameter values, similar to a lookup table.
# You can match a key to a corresponding value by using the Fn::FindInMap intrinsic function in the Resources and Outputs sections.
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html
Mappings: set of mappings

# Conditions that control whether certain resources are created or whether certain resource properties are assigned a value during stack creation or update.
# For example, you could conditionally create a resource that depends on whether the stack is for a production or test environment.
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html
Conditions: set of conditions

# For serverless applications (also referred to as Lambda-based applications), specifies the version of the AWS Serverless Application Model (AWS SAM) to use.
# When you specify a transform, you can use AWS SAM syntax to declare resources in your template.
# The model defines the syntax that you can use and how it's processed.
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform: set of transforms

# Specifies the stack resources and their properties, such as an Amazon Elastic Compute Cloud instance or an Amazon Simple Storage Service bucket.
# You can refer to resources in the Resources and Outputs sections of the template.
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources: set of resources

# Describes the values that are returned whenever you view your stack's properties.
# For example, you can declare an output for an S3 bucket name and then call the aws cloudformation describe-stacks AWS CLI command to view the name.
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
Outputs: set of outputs
