exclude: "^$"
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      # forbid files which have a UTF-8 byte-order marker
      - id: fix-byte-order-marker
      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict
      # This hook checks json files for parseable syntax.
      - id: check-json
      # Check for files that contain merge conflict strings.
      - id: check-merge-conflict
      # Checks for symlinks which do not point to anything.
      - id: check-symlinks
      # This hook checks toml files for parseable syntax.
      - id: check-toml
      # Ensures that links to vcs websites are permalinks.
      - id: check-vcs-permalinks
      # This hook checks xml files for parseable syntax.
      - id: check-xml
      # This hook checks yaml files for parseable syntax.
      - id: check-yaml
      # Detects symlinks which are changed to regular files with a content of a path which that symlink was pointing to.
      - id: destroyed-symlinks
      # Detects the presence of private keys
      - id: detect-private-key
      # Ensures that a file is either empty, or ends with one newline.
      - id: end-of-file-fixer
      # Replaces or checks mixed line ending
      - id: mixed-line-ending
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: pretty-format-json
        args: ["--autofix", "--indent", "2", "--no-sort-keys"]
      # This hook trims trailing whitespace.
      - id: trailing-whitespace

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.0
    hooks:
      # Rewrites all Terraform configuration files to a canonical format.
      - id: terraform_fmt
      # Validates all Terraform configuration files.
      - id: terraform_validate
      # Validates all Terraform configuration files with TFLint.
      - id: terraform_tflint
      # TFSec static analysis of terraform templates to spot potential security issues.
      - id: terraform_tfsec
    # checkov static analysis of terraform templates to spot potential security issues.
    #- id: terraform_checkov
    # terrascan Detect compliance and security violations.
    #- id: terrascan
